array_width = 120
attr_fn_like_width = 100
chain_width = 120
comment_width = 120
fn_call_width = 100
fn_single_line = true
max_width = 120
imports_granularity = "Module"
single_line_if_else_max_width = 120
where_single_line = true
wrap_comments = true
